lib/luna_app_web/router.ex
defmodule LunaAppWeb.Router do
  use LunaAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LunaAppWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LunaAppWeb do
    pipe_through :browser

    get "/", OpenGraphController, :index
    resources "/open_graphs", OpenGraphController, only: [:index, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", LunaAppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: LunaAppWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/luna_app/open_graphs.ex
defmodule LunaApp.OpenGraphs do
  @moduledoc """
  The OpenGraphs context.
  """

  import Ecto.Query, warn: false
  alias LunaApp.Repo

  alias LunaApp.OpenGraphs.OpenGraph
  alias LunaApp.OpenGraphs.Parser

  @doc """
  Gets a single open_graph.

  Raises `Ecto.NoResultsError` if the Open graph does not exist.

  ## Examples

      iex> get_open_graph!(123)
      %OpenGraph{}

      iex> get_open_graph!(456)
      ** (Ecto.NoResultsError)

  """
  def get_open_graph!(id), do: Repo.get!(OpenGraph, id)

  def get_open_graph_by_url!(url), do: Repo.get_by!(OpenGraph, url: url)

  @doc """
  Creates a open_graph.

  ## Examples

      iex> create_open_graph(%{field: value})
      {:ok, %OpenGraph{}}

      iex> create_open_graph(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_open_graph(attrs \\ %{}) do
    %OpenGraph{}
    |> OpenGraph.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Create if not recorded found by url
  or return the existing one
  """
  def upsert_open_graph(%{url: url} = attrs) do
    conflict_target = [:url]
    on_conflict_changes = [updated_at: DateTime.utc_now()]

    on_conflict =
      OpenGraph
      |> where([g], g.url == ^attrs.url)
      |> update(set: ^on_conflict_changes)

    graph =
      %OpenGraph{}
      |> OpenGraph.changeset(attrs)
      |> Repo.insert!(
        on_conflict: on_conflict,
        conflict_target: conflict_target,
        returning: true
      )

    {:ok, graph}
  end

  @doc """
  Updates a open_graph.

  ## Examples

      iex> update_open_graph(open_graph, %{field: new_value})
      {:ok, %OpenGraph{}}

      iex> update_open_graph(open_graph, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_open_graph(%OpenGraph{} = open_graph, attrs) do
    open_graph
    |> OpenGraph.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking open_graph changes.

  ## Examples

      iex> change_open_graph(open_graph)
      %Ecto.Changeset{data: %OpenGraph{}}

  """
  def change_open_graph(%OpenGraph{} = open_graph, attrs \\ %{}) do
    OpenGraph.changeset(open_graph, attrs)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking open_graph changes.

  """
  def async_fetch(%OpenGraph{status: "pending"} = open_graph) do
    update_open_graph(open_graph, %{status: "processing"})
    Task.async(fn -> Parser.fetch(open_graph) end)
    {:ok, open_graph}
  end
end

lib/luna_app/open_graphs/open_graph.ex
defmodule LunaApp.OpenGraphs.OpenGraph do
  use Ecto.Schema
  import Ecto.Changeset

  schema "open_graphs" do
    field :url, :string
    field :image, :string
    field :title, :string, default: ""
    field :type, :string, default: "website"
    field :status, :string, default: "pending"
    field :metadata, :map, default: nil

    timestamps()
  end

  @doc false
  @changeset_params [:id, :url, :image, :title, :type, :status, :metadata]
  @allowed_status [
    "pending",
    "processing",
    "ready",
    "error"
  ]
  def changeset(open_graph, attrs) do
    open_graph
    |> cast(attrs, @changeset_params)
    |> validate_required([:url, :status])
    |> validate_inclusion(:status, @allowed_status)
  end
end

lib/luna_app/open_graphs/parser.ex
defmodule LunaApp.OpenGraphs.Parser do
  alias LunaApp.OpenGraphs
  alias LunaApp.OpenGraphs.OpenGraph, as: Graph

  def fetch(%Graph{url: url} = graph) do
    # Process.sleep(3000)

    case OpenGraph.fetch(url) do
      {:ok, og} ->
        raw_params = Map.from_struct(og)
        params = Map.merge(raw_params, %{url: url, status: "ready", metadata: raw_params})
        OpenGraphs.update_open_graph(graph, params)

      _ ->
        OpenGraphs.update_open_graph(graph, %{status: "error"})
    end
  end
end

lib/luna_app_web/controllers/open_graph_controller.ex
defmodule LunaAppWeb.OpenGraphController do
  use LunaAppWeb, :controller

  alias LunaApp.OpenGraphs
  alias LunaApp.OpenGraphs.OpenGraph

  def index(conn, _params) do
    changeset = OpenGraphs.change_open_graph(%OpenGraph{})
    render(conn, "new.html", changeset: changeset, open_graph: nil)
  end

  def create(conn, %{"open_graph" => %{"url" => url} = params}) do
    sanitized = sanitize_url(url)

    case OpenGraphs.upsert_open_graph(%{url: sanitized}) do
      {:ok, %OpenGraph{status: "pending"} = open_graph} ->
        OpenGraphs.async_fetch(open_graph)
        render_create(conn, %{open_graph: open_graph})

      {:ok, open_graph} ->
        render_create(conn, %{open_graph: open_graph})
    end
  end

  defp render_create(conn, %{open_graph: open_graph}) do
    conn
    |> assign(:open_graph, open_graph)
    |> render("new.html",
      changeset: OpenGraphs.change_open_graph(%OpenGraph{}, Map.from_struct(open_graph)),
      open_graph: open_graph
    )
  end

  defp sanitize_url(url) do
    uri = url |> String.trim() |> URI.parse() |> URI.to_string()
  end
end

lib/luna_app_web/views/open_graph_view.ex
defmodule LunaAppWeb.OpenGraphView do
  use LunaAppWeb, :view
end

lib/luna_app_web/templates/open_graph/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
    {IO.inspect(@changeset)}
  <% end %>

  <%= label f, "Input an \"URL\" to inspect Open Graph preview" %>
  <%= text_input f, :url, placeholder: "eg: https://ogp.me/" %>
  <%= error_tag f, :url %>

  <div>
    <%= submit "Preview" %>
  </div>

  <%= if g = @conn.assigns[:open_graph] do %>
    <%= if g.status == "pending" || g.status == "processing" do %>
    <p> in progress ... 
    please check this later <p>
    <% end %>
    
    <%= if g.status == "ready" do %>
    <div>
      <h1> Preview </h1>
      <img src={g.image} alt="image here"/>
      <ul>
        <li><b>Url</b>: <%= g.url %></li>
        <li><b>Title</b>: <%= g.title %></li>
        <li><b>Type</b>: <%= g.type %></li>
        <%!-- <li><b>imag_url</b>: <%= g.image %></li> --%>
      </ul>
    </div>
    <% end %>
    <%= if g.status == "error" do %>
    <div style="background-color:Tomato;">
      <p > <b> Something went Wrong!</b> </p>
      <p> Please make sure the website support OG meta data or the url is correct!</p>
      <p> Clean up DB & try it again! </p>
    </div>
    <% end %>
  <% end %>
</.form>

lib/luna_app_web/templates/open_graph/index.html.heex
<h1>Open Graph Preview</h1>




<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Image url</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for open_graph <- @open_graphs do %>
    <tr>
      <td><%= open_graph.url %></td>
      <td><%= open_graph.image %></td>

      <td>
        <span><%= link "Show", to: Routes.open_graph_path(@conn, :show, open_graph) %></span>
        <span><%= link "Edit", to: Routes.open_graph_path(@conn, :edit, open_graph) %></span>
        <span><%= link "Delete", to: Routes.open_graph_path(@conn, :delete, open_graph), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%!-- <span><%= link "New Open graph", to: Routes.open_graph_path(@conn, :new) %></span> --%>

lib/luna_app_web/templates/open_graph/new.html.heex
<h1>Open Graph Preview</h1>

<%!-- <h1> <%= @conn.assigns[:graph][:url] %> </h1> --%>
<%= render "form.html", Map.put(assigns, :action, Routes.open_graph_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.open_graph_path(@conn, :index) %></span>